# Generated by Django 2.0.13 on 2019-04-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('areanegocio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoDpto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='Sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='empleadodpto',
            name='Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Empleado'),
        ),
    ]
