# Generated by Django 2.0.13 on 2019-04-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_ventaproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='fecha',
            new_name='fechaventa',
        ),
    ]
