# Generated by Django 2.0.13 on 2019-04-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20190426_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproducto',
            old_name='fechaventa',
            new_name='fecha',
        ),
    ]
